wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.11.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1648633785
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      2:
      - 1
      - 5
      - 11
      - 49
      3:
      - 2
      - 16
      4: 3.9.7
      5: 0.12.11
      6: 4.11.3
      8:
      - 2
      - 5
method:
  desc: null
  value: random
metric:
  desc: null
  value:
    goal: minimize
    name: loss
parameters:
  desc: null
  value:
    dropout:
      values:
      - 0.3
      - 0.4
      - 0.5
    epochs:
      value: 1
    fc_layer_size:
      values:
      - 128
      - 256
      - 512
    optimizer:
      values:
      - adam
      - sgd
