wandb_version: 1

_wandb_kernel:
  value: mkingo
apex:
  value: 'true'
batch_scheduler:
  value: 'false'
batch_size:
  value: 90
competition:
  value: NBME
debug:
  value: 'true'
decoder_lr:
  value: 4.873265500692282e-05
encoder_lr:
  value: 2.466649058609857e-05
epochs:
  value: 20
eps:
  value: 1.9095049869617244e-06
fc_dropout:
  value: 0.35547443197930606
gradient_accumulation_steps:
  value: 1
max_grad_norm:
  value: 4717
max_len:
  value: 1192
min_lr:
  value: 1.6846446676439065e-06
model:
  value: microsoft/deberta-base
n_fold:
  value: 3
num_cycles:
  value: 1.602817449167715
num_workers:
  value: 3
print_freq:
  value: 525
scheduler:
  value: cosine
seed:
  value: 87
tokenizer:
  value: single_word=False
train:
  value: 'false'
wandb:
  value: 'true'
weight_decay:
  value: 0.010064084806901396
