wandb_version: 1

_wandb_kernel:
  value: mkingo
apex:
  value: 'true'
batch_scheduler:
  value: 'true'
batch_size:
  value: 22
competition:
  value: NBME
debug:
  value: 'false'
decoder_lr:
  value: 2.2531317389839777e-05
encoder_lr:
  value: 3.599769199027391e-05
epochs:
  value: 14
eps:
  value: 4.670801507743619e-07
fc_dropout:
  value: 0.30413605216495243
gradient_accumulation_steps:
  value: 2
max_grad_norm:
  value: 2725
max_len:
  value: 1338
min_lr:
  value: 1.363326422687548e-06
model:
  value: microsoft/deberta-base
n_fold:
  value: 8
num_cycles:
  value: 0.456135975463416
num_workers:
  value: 1
print_freq:
  value: 266
scheduler:
  value: cosine
seed:
  value: 49
tokenizer:
  value: single_word=False
train:
  value: 'false'
wandb:
  value: 'true'
weight_decay:
  value: 0.0072502065856156
