wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.11.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1647673653
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      2:
      - 1
      - 5
      - 11
      - 49
      3:
      - 2
      - 13
      - 16
      4: 3.9.7
      5: 0.12.11
      6: 4.11.3
      8:
      - 2
      - 5
_wandb_kernel:
  desc: null
  value: mkingo
apex:
  desc: null
  value: 'true'
batch_scheduler:
  desc: null
  value: 'true'
batch_size:
  desc: null
  value: 16
betas:
  desc: null
  value:
  - 0.9
  - 0.999
competition:
  desc: null
  value: NBME
debug:
  desc: null
  value: 'true'
decoder_lr:
  desc: null
  value: 2.877276748110329e-05
encoder_lr:
  desc: null
  value: 3.096848077592162e-05
epochs:
  desc: null
  value: 7
eps:
  desc: null
  value: 8.088650714923146e-07
fc_dropout:
  desc: null
  value: 0.32681782116113733
gradient_accumulation_steps:
  desc: null
  value: 1
max_grad_norm:
  desc: null
  value: 691
max_len:
  desc: null
  value: 778
min_lr:
  desc: null
  value: 7.531647160365293e-07
model:
  desc: null
  value: microsoft/deberta-base
n_fold:
  desc: null
  value: 10
num_cycles:
  desc: null
  value: 0.9864656395156524
num_warmup_steps:
  desc: null
  value: 0
num_workers:
  desc: null
  value: 4
print_freq:
  desc: null
  value: 105
scheduler:
  desc: null
  value: cosine
seed:
  desc: null
  value: 68
tokenizer:
  desc: null
  value: single_word=False
train:
  desc: null
  value: 'false'
trn_fold:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
wandb:
  desc: null
  value: 'true'
weight_decay:
  desc: null
  value: 0.00749585687054166
