wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.14.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.11
    start_time: 1649277009
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      2:
      - 1
      - 5
      - 11
      - 49
      3:
      - 2
      4: 3.9.11
      5: 0.12.11
      6: 4.14.1
      8:
      - 2
      - 5
